const lessons = {
  branching: { title: 'Branching', level: 'Foundation', time: '12 min read + practice', summary: 'A branch is an independent line of work. Use one to build a feature or fix a bug without disturbing the stable main branch.', overview: 'Think of main as the version your team trusts. Before changing anything, create a branch with a clear name. Your commits stay on that branch until you are ready to share and merge them.', workflow: ['Start from an up-to-date main branch.', 'Create a descriptive branch, such as feature/login-form or fix/mobile-menu.', 'Make one focused change, test it, and commit with a message that explains why.', 'Push the branch and open a pull request instead of pushing directly to main.'], commands: `git switch main\ngit pull origin main\ngit switch -c feature/profile-card\n# edit files, then:\ngit add .\ngit commit -m "Add responsive profile card"\ngit push -u origin feature/profile-card`, mistakes: ['Do not use one branch for unrelated tasks.', 'Do not commit generated secrets such as .env files; add them to .gitignore.', 'Before creating a branch, update main so you start from current team work.'], exercise: 'Create a test repository. Make a branch named feature/welcome-message, add one sentence to a file, commit it, then switch back to main and run git log --oneline --all.' },
  'pull-requests': { title: 'Pull Requests', level: 'Collaboration', time: '14 min read + practice', summary: 'A pull request (PR) is a proposed change on GitHub. It gives teammates a place to understand, discuss, review, and safely merge your work.', overview: 'A PR compares your branch with a target branch, usually main. It is not merely a request to merge: it is a written record of the decision, the testing, and the review.', workflow: ['Push your branch to GitHub.', 'Open a PR into main with a specific title: “Add keyboard navigation to menu”.', 'Write what changed, why it changed, and how you tested it.', 'Request the appropriate reviewer, respond to feedback, then merge only when checks and approvals are complete.'], commands: `git push -u origin feature/profile-card\n# On GitHub: Compare & pull request\n# After review and merge:\ngit switch main\ngit pull origin main\ngit branch -d feature/profile-card`, mistakes: ['Avoid huge PRs that mix refactoring, new features, and formatting changes.', 'Never leave the PR description empty; reviewers need context.', 'Do not merge when required checks fail or important feedback is unresolved.'], exercise: 'Push a small branch to a GitHub repository. Open a PR using the template: What changed? Why? How did I test it? Ask a classmate to leave one comment.' },
  'merge-conflicts': { title: 'Merge Conflicts', level: 'Problem solving', time: '16 min read + practice', summary: 'A merge conflict means Git found two changes to the same area and needs a human decision. It is normal teamwork, not a failure.', overview: 'Git usually merges automatically. A conflict appears only when Git cannot safely choose between versions. Read both changes, understand the intended final result, edit the file, test it, and mark it resolved.', workflow: ['Pull the latest target branch into your branch or update it through your PR.', 'Open every conflicted file and find the <<<<<<<, =======, and >>>>>>> markers.', 'Keep, combine, or rewrite the correct code. Remove all conflict markers.', 'Test the result, stage the resolved files, and complete the merge or rebase.'], commands: `git status\n# edit the files Git lists\ngit add path/to/resolved-file\ngit commit\n# If you started a rebase instead:\ngit rebase --continue\n# Safely abandon the operation if needed:\ngit merge --abort`, mistakes: ['Never delete conflict markers blindly before reading both sides.', 'Do not resolve a conflict you do not understand; ask the author or reviewer.', 'Run the app or tests after resolving - a clean Git state does not guarantee correct behaviour.'], exercise: 'In a practice repo, change the same line differently on main and a new branch. Merge the branch, resolve the conflict by combining both ideas, and check git status.' },
  'code-reviews': { title: 'Code Reviews', level: 'Quality', time: '13 min read + practice', summary: 'Code review is a collaborative quality check. Good reviews make code safer, clearer, and easier for the next person to maintain.', overview: 'Review the PR description first, then inspect the smallest meaningful parts of the diff. Focus on correctness, user impact, security, tests, readability, and alignment with the task - not personal style preferences.', workflow: ['Read the goal and test plan in the PR description.', 'Review in small passes: architecture first, then behaviour, then details.', 'Leave comments that explain the concern and invite a solution.', 'Approve when you are confident, or request changes when a blocking issue remains.'], commands: `# Helpful local review commands\ngit fetch origin\ngit switch feature/profile-card\ngit diff main...HEAD\ngit log --oneline main..HEAD`, mistakes: ['Do not write vague comments like “wrong” or “fix this”. Explain the risk.', 'Label minor suggestions as non-blocking so the author knows the priority.', 'Do not approve code you have not understood or tested when testing is expected.'], exercise: 'Ask a friend for a small PR. Leave one praise comment, one question, and one actionable suggestion using: “Could we … because … ?”' },
  'github-issues': { title: 'GitHub Issues', level: 'Planning', time: '11 min read + practice', summary: 'Issues turn bugs, ideas, and tasks into work your team can see, discuss, assign, and track from start to finish.', overview: 'An issue is not automatically a bug. It can capture a feature request, question, documentation improvement, or technical task. A useful issue gives the next person enough context to begin.', workflow: ['Use a short, outcome-based title: “Navigation overlaps content on mobile”.', 'Describe the problem, expected result, and any reproduction steps or screenshots.', 'Add labels such as bug, enhancement, documentation, or good first issue.', 'Assign an owner, link the issue to a PR, and close it only when the work is truly complete.'], commands: `# GitHub CLI (optional)\ngh issue create --title "Fix mobile navigation overlap" --body "Steps to reproduce..."\ngh issue list --label bug\n# In a commit or PR description, link it with: Fixes #12`, mistakes: ['Avoid titles like “Bug” that do not explain the outcome.', 'Do not put passwords, tokens, or private customer data in a public issue.', 'Avoid closing an issue only because a PR exists; close it after the merged change solves it.'], exercise: 'Create two issues: one bug report with reproduction steps and one feature request with acceptance criteria. Add labels and connect one to a test PR.' },
  'project-boards': { title: 'Project Boards', level: 'Workflow', time: '10 min read + practice', summary: 'GitHub Projects gives your team a shared board for planning work. It makes priorities, ownership, and progress visible without a status-meeting maze.', overview: 'Start with a small workflow: Backlog, Ready, In progress, In review, and Done. Add issues and pull requests as items so the board reflects the actual work, not a second copy of it.', workflow: ['Create a GitHub Project and add status fields that match your team workflow.', 'Add each issue as an item, then set a priority and an owner.', 'Move only active work into In progress; this reveals real capacity.', 'Review the board regularly, archive completed work, and adjust priorities together.'], commands: `# GitHub CLI can help you explore project commands\ngh project list --owner YOUR-USERNAME\n# Most beginners should create and configure Projects in GitHub's web interface.\n# Link issues and PRs from their sidebar or the project Add item menu.`, mistakes: ['Do not create too many columns; a board should make the next action obvious.', 'Do not mark work “In progress” unless someone has actually started it.', 'Do not maintain task status in several places; choose the board as the shared source of truth.'], exercise: 'Create a project with the five workflow columns. Add your two practice issues, assign priorities, and move one from Ready to In progress when you begin it.' }
};

const key = new URLSearchParams(window.location.search).get('feature');
const lesson = lessons[key] || lessons.branching;
document.title = `GitPractice | ${lesson.title}`;
document.querySelector('#lesson-hero').innerHTML = `<span class="lesson-label">${lesson.level} lesson</span><h1>${lesson.title}</h1><p>${lesson.summary}</p><div class="lesson-meta"><span>⌛ ${lesson.time}</span><span>◉ Practical Git + GitHub</span></div>`;
document.querySelector('#lesson-content').innerHTML = `
  <section id="overview"><h2>What you need to know</h2><p>${lesson.overview}</p><div class="callout"><strong>Student tip</strong><p>Use a disposable practice repository while learning. You can experiment freely without risking an important project.</p></div></section>
  <section id="workflow"><h2>A practical workflow</h2><ol class="steps">${lesson.workflow.map(step => `<li>${step}</li>`).join('')}</ol></section>
  <section id="commands"><h2>Commands to practise</h2><p>Run these from the terminal inside your repository. Lines beginning with <code>#</code> are notes, not commands.</p><div class="command"><span class="command-title">Terminal</span><pre><code>${lesson.commands}</code></pre></div></section>
  <section id="mistakes"><h2>Common mistakes to avoid</h2><ul>${lesson.mistakes.map(mistake => `<li>${mistake}</li>`).join('')}</ul></section>
  <section id="exercise" class="exercise"><p class="eyebrow">Hands-on challenge</p><h2>Try it yourself</h2><p>${lesson.exercise}</p><label class="exercise-check"><input id="done-check" type="checkbox"> I completed this practice task.</label><p id="completion" class="completion">Nice work. The fastest way to master Git is to repeat this workflow on your next real task.</p></section>`;
document.querySelector('#done-check').addEventListener('change', (event) => document.querySelector('#completion').classList.toggle('show', event.target.checked));
